//跳转销售界面
export const TOPRESALE = 'HOME/TOPRESALE';
export const ACTIVETICKET = 'HOME/ACTIVETICKET';

//收银上缴
export const TRANSFER = 'HOME/TRANSFER';

// 脱机
export const CHENGEONLINEOFF = 'HOME/CHENGEONLINEOFF';
//联网
export const CHENGEONLINEON = 'HOME/CHENGEONLINEON';
//断网
export const CHENGEONLINENO = 'HOME/CHENGEONLINENO';
//人为操作
// 为人为操作
export const HUMANINTERVENTIONTRUE = 'HOME/HUMANINTERVENTIONTRUE';
// 注销人为操作
export const HUMANINTERVENTIONFALSE = 'HOME/HUMANINTERVENTIONFALSE';